apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kpn-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kpn-app
        track: canary
        version: 1.0.0
    spec:
      containers:
        - name: kpn-canary
          image: linuxacademycontent/content-gcp-labs:deploy-canary
          ports:
            - name: http
              containerPort: 80
